#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1525524445                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/id1525524445      # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.thehelpingcompany.donut                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "Donut: Coloring Book for Kids"             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           :

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : The Helping Company
your_link                                 : https://www.thehelpingcompany.com
your_city                                 :
email_address                             :
facebook_username                         :
instagram_username                        : thehelpingcompany
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Drawing is thinking made visible
    description                           : Donut is a place for your child to express themselves and explore their imagination with drawing and coloring. Absolutely no ads.
    fontawesome_icon_name                 : paint-brush

  - title                                 : Designed by artists and teachers
    description                           : A minimalist and unstructured approach to increase concentration, stimulate creativity and improve memory for young children.
    fontawesome_icon_name                 : shapes

  - title                                 : Thoughtfully crafted, expertly curated
    description                           : Over 750+ pages of drawing, coloring and learning activities, continuously updated and reviewed by child development experts.
    fontawesome_icon_name                 : pencil-ruler




# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.0
topbar_title_color                        : "#191919"

cover_image                               :                                           # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#191919"
app_price_color                           : "#ffffff"
app_description_color                     : "#191919"

feature_title_color                       : "#191919"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#191919"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
